version: '3'

services:
  postgresql:
    image: postgres
    container_name: techjs
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=techjs
      - POSTGRES_PASSWORD=techjs
      - POSTGRES_DATABASE=techjs
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-techjs
    ports:
      - '6379-6379'